[package]
name = "quadrupel-rs"
version = "0.1.0"
edition = "2021"
build = "build/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = {version = "0.7.4", features = ["inline-asm"]}
cortex-m-rt = "0.6.15"
nrf51822 = {path = "./sdk/nrf51822", features = ["rt"]}
#cortex-m-semihosting = "0.5.0"

[profile.release]
incremental = false

[profile.dev]
incremental = false

[profile.test]
incremental = false

[profile.bench]
incremental = false
